appizens_shop:
    resource: "@AppizensShopBundle/Resources/config/routing.yml"
    prefix:   /

assignment:
    resource: "@AssignmentBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
