<?php

namespace Appizens\AssignmentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OperationTheaterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DutyTimeRepository extends EntityRepository
{
    public function isOnDuty($userId, $startTime, $endTime){
        //@todo check user is on duty or not
     $dutiTimes=   $this->createQueryBuilder('d')
             ->andWhere('d.user=:user')
             ->setParameter('user',$userId )
             ->andWhere('d.dutyStartAt<=:start')
             ->andWhere('d.dutyEndAt<=:end')
             ->setParameter('start',$startTime)
             ->setParameter('end',$endTime)
             ->getQuery()
             ->getResult();

        if(!empty($dutiTimes))
            return true;
    }
}
