<?php

namespace Appizens\AssignmentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OperationTheaterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationTheaterRepository extends EntityRepository
{
}
